const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const Analysis = require('../models/Analysis');
const Report = require('../models/Report');
const { getFilePath } = require('./storage');

async function generateReport(analysisId, userId) {
  const analysis = await Analysis.findById(analysisId)
    .populate('videoId')
    .populate('requestedBy', 'name email');

  if (!analysis) {
    throw new Error('Analysis not found');
  }

  const filename = `report_${analysisId}_${Date.now()}.pdf`;
  const filePath = getFilePath('reports', filename);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const stream = fs.createWriteStream(filePath);

    doc.pipe(stream);

    const lineColor = '#34d399';
    const gray = '#6b7280';
    const black = '#000000';

    // ================= Header =================
    doc.fontSize(24).font('Helvetica-Bold').fillColor(black).text('WildShield AI', { align: 'center' });
    doc.moveDown(0.2);
    doc.fontSize(11).font('Helvetica').fillColor(gray).text('Wildlife & Forest Video Security Analysis Report', { align: 'center' });
    doc.moveDown(0.8);
    drawDivider(doc, lineColor);
    doc.moveDown(0.8);

    // ================= Video Information =================
    doc.fontSize(15).font('Helvetica-Bold').fillColor(black).text('Video Information');
    doc.moveDown(0.6);

    const video = analysis.videoId;
    const infoLines = [
      ['File:', video.originalName || video.filename],
      ['Size:', formatSize(video.size)],
      ['Uploaded by:', analysis.requestedBy?.name || 'Unknown'],
      ['Analysis date:', formatDate(analysis.createdAt)],
      ['Processing time:', analysis.processingTimeMs ? Math.round(analysis.processingTimeMs) + 'ms' : 'N/A'],
    ];

    doc.fontSize(11);
    infoLines.forEach(([label, value]) => {
      const rowY = doc.y;
      doc.font('Helvetica-Bold').fillColor(black).text(label, 50, rowY, { width: 130, continued: true });
      doc.font('Helvetica').fillColor(black).text(String(value), { lineBreak: true });
      doc.moveDown(0.4);
    });

    doc.moveDown(0.6);
    drawDivider(doc, lineColor);
    doc.moveDown(0.8);

    // ================= Analysis Result =================
    const result = analysis.threatResult || {};
    const harm = result.verdict === 'ANIMAL_HARM_DETECTED';

    doc.fontSize(15).font('Helvetica-Bold').fillColor(black).text('Analysis Result', { align: 'center' });
    doc.moveDown(0.8);

    if (harm) {
      doc.font('Helvetica-Bold').fillColor('#ef4444').fontSize(20).text('⚠ ATTACK DETECTED', { align: 'center' });
    } else {
      doc.font('Helvetica-Bold').fillColor('#16a34a').fontSize(20).text('No Attacks Detected', { align: 'center' });
    }
    doc.moveDown(0.7);
    doc.font('Helvetica').fillColor(black).fontSize(12).text(
      result.message || (harm ? 'Attack detected.' : 'No attacks detected.'),
      { align: 'center' }
    );

    doc.moveDown(1.2);

    // ================= Footer =================
    doc.moveDown(2);
    const footerY = Math.max(doc.y, doc.page.height - doc.page.margins.bottom - 120);
    drawDivider(doc, lineColor, footerY);
    doc.moveDown(0.5);
    doc.fontSize(9).font('Helvetica').fillColor(gray).text(
      'DISCLAIMER: This report is generated by an AI system and is intended as decision-support only. ' +
      'All findings must be verified by authorized personnel before any action is taken.',
      { align: 'center', lineGap: 4 }
    );
    doc.moveDown(0.6);
    doc.text(`Generated: ${new Date().toISOString()}  |  WildShield AI v0.2.0`, { align: 'center' });

    doc.end();

    stream.on('finish', async () => {
      try {
        const stats = fs.statSync(filePath);
        const report = await Report.create({
          analysisId,
          generatedBy: userId,
          filename,
          path: filePath,
          fileSize: stats.size,
        });
        await Analysis.findByIdAndUpdate(analysisId, { reportPath: filePath });
        resolve(report);
      } catch (err) {
        reject(err);
      }
    });

    stream.on('error', reject);
  });
}

function drawDivider(doc, color, y) {
  const rowY = y !== undefined ? y : doc.y;
  doc.save();
  doc.moveTo(50, rowY).lineTo(545, rowY).stroke(color);
  doc.restore();
}

function formatDate(date) {
  if (!date) return 'N/A';
  return date.toLocaleString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function formatSize(bytes) {
  if (!bytes) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  let i = 0;
  let size = bytes;
  while (size >= 1024 && i < units.length - 1) {
    size /= 1024;
    i++;
  }
  return `${size.toFixed(1)} ${units[i]}`;
}

module.exports = { generateReport };
