const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const Analysis = require('../models/Analysis');
const Report = require('../models/Report');
const { getFilePath } = require('./storage');

async function generateReport(analysisId, userId) {
  const analysis = await Analysis.findById(analysisId)
    .populate('videoId')
    .populate('requestedBy', 'name email');

  if (!analysis) {
    throw new Error('Analysis not found');
  }

  const filename = `report_${analysisId}_${Date.now()}.pdf`;
  const filePath = getFilePath('reports', filename);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const stream = fs.createWriteStream(filePath);

    doc.pipe(stream);

    // Header
    doc.fontSize(22).font('Helvetica-Bold').text('WildShield AI', { align: 'center' });
    doc.fontSize(10).font('Helvetica').fillColor('#666').text('Wildlife & Forest Video Security Analysis Report', { align: 'center' });
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#34d399');
    doc.moveDown(1);

    // Video info
    doc.fontSize(14).font('Helvetica-Bold').fillColor('#000').text('Video Information');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica');
    const video = analysis.videoId;
    doc.text(`File: ${video.originalName || video.filename}`);
    doc.text(`Size: ${formatSize(video.size)}`);
    doc.text(`Uploaded by: ${analysis.requestedBy?.name || 'Unknown'}`);
    doc.text(`Analysis date: ${analysis.createdAt.toLocaleDateString()}`);
    doc.text(`Processing time: ${analysis.processingTimeMs ? Math.round(analysis.processingTimeMs) + 'ms' : 'N/A'}`);
    doc.moveDown(1);

    // Verdict
    const result = analysis.threatResult || {};
    const harm = result.verdict === 'ANIMAL_HARM_DETECTED';

    doc.fontSize(14).font('Helvetica-Bold').text('Analysis Result');
    doc.moveDown(0.3);
    if (harm) {
      doc.fillColor('#ef4444').font('Helvetica-Bold').fontSize(16).text('⚠ ANIMAL HARM DETECTED');
    } else {
      doc.fillColor('#22c55e').font('Helvetica-Bold').fontSize(16).text('No Threat Detected');
    }
    doc.moveDown(0.5);
    doc.fillColor('#000').font('Helvetica').fontSize(10);
    doc.text(result.message || (harm ? 'An animal harm/attack event was detected in this video.' : 'No animal attack, harm, or abuse was detected.'));

    if (harm && result.incident) {
      const inc = result.incident;
      doc.moveDown(1);
      doc.fontSize(14).font('Helvetica-Bold').text('Incident Details');
      doc.moveDown(0.3);
      doc.fontSize(10).font('Helvetica');
      doc.text(`Incident type: ${inc.incident_type || 'Unknown'}`);
    }

    doc.moveDown(1);

    // Disclaimer
    doc.fontSize(8).font('Helvetica').fillColor('#999');
    doc.text(
      'DISCLAIMER: This report is generated by an AI system and is intended as decision-support only. ' +
      'All findings must be verified by authorized personnel before any action is taken.',
      50,
      doc.y,
      { width: 495 }
    );

    doc.moveDown(0.5);
    doc.text(`Generated: ${new Date().toISOString()} | WildShield AI v0.2.0`);

    doc.end();

    stream.on('finish', async () => {
      try {
        const stats = fs.statSync(filePath);
        const report = await Report.create({
          analysisId,
          generatedBy: userId,
          filename,
          path: filePath,
          fileSize: stats.size,
        });
        await Analysis.findByIdAndUpdate(analysisId, { reportPath: filePath });
        resolve(report);
      } catch (err) {
        reject(err);
      }
    });

    stream.on('error', reject);
  });
}

function formatSize(bytes) {
  if (!bytes) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  let i = 0;
  let size = bytes;
  while (size >= 1024 && i < units.length - 1) {
    size /= 1024;
    i++;
  }
  return `${size.toFixed(1)} ${units[i]}`;
}

module.exports = { generateReport };