const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const Analysis = require('../models/Analysis');
const Video = require('../models/Video');
const Report = require('../models/Report');
const { getFilePath } = require('./storage');

const THREAT_COLORS = {
  CRITICAL: '#f87171',
  HIGH: '#fb923c',
  MEDIUM: '#fbbf24',
  LOW: '#4ade80',
  NONE: '#6b7280',
};

async function generateReport(analysisId, userId) {
  const analysis = await Analysis.findById(analysisId)
    .populate('videoId')
    .populate('requestedBy', 'name email');

  if (!analysis) {
    throw new Error('Analysis not found');
  }

  const filename = `report_${analysisId}_${Date.now()}.pdf`;
  const filePath = getFilePath('reports', filename);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const stream = fs.createWriteStream(filePath);

    doc.pipe(stream);

    // Header
    doc.fontSize(22).font('Helvetica-Bold').text('WildShield AI', { align: 'center' });
    doc.fontSize(10).font('Helvetica').fillColor('#666').text('Wildlife & Forest Video Security Analysis Report', { align: 'center' });
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#34d399');
    doc.moveDown(1);

    // Video info
    doc.fontSize(14).font('Helvetica-Bold').fillColor('#000').text('Video Information');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica');
    const video = analysis.videoId;
    doc.text(`File: ${video.originalName || video.filename}`);
    doc.text(`Size: ${formatSize(video.size)}`);
    doc.text(`Uploaded by: ${analysis.requestedBy?.name || 'Unknown'}`);
    doc.text(`Analysis date: ${analysis.createdAt.toLocaleDateString()}`);
    doc.text(`Processing time: ${analysis.processingTimeMs ? Math.round(analysis.processingTimeMs) + 'ms' : 'N/A'}`);
    doc.moveDown(1);

    // Summary
    const summary = analysis.summary || {};
    doc.fontSize(14).font('Helvetica-Bold').text('Analysis Summary');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica');
    doc.text(`Status: ${analysis.status.toUpperCase()}`);
    doc.text(`Total detections: ${summary.totalDetections || 0}`);
    doc.text(`Threats found: ${summary.threatsFound || 0}`);
    doc.text(`Highest threat level: ${summary.highestThreat || 'NONE'}`);
    doc.text(`Frames analyzed: ${summary.framesAnalyzed || 0} / ${summary.totalFrames || 0}`);
    if (summary.uniqueLabels && summary.uniqueLabels.length > 0) {
      doc.text(`Labels detected: ${summary.uniqueLabels.join(', ')}`);
    }
    doc.moveDown(1);

    // Threat breakdown
    if (summary.totalDetections > 0) {
      doc.fontSize(14).font('Helvetica-Bold').text('Threat Breakdown');
      doc.moveDown(0.3);
      doc.fontSize(10).font('Helvetica');

      const detections = analysis.detections || [];
      const byLevel = {};
      for (const d of detections) {
        const level = d.threatLevel || 'NONE';
        if (!byLevel[level]) byLevel[level] = [];
        byLevel[level].push(d);
      }

      for (const [level, dets] of Object.entries(byLevel)) {
        const color = THREAT_COLORS[level] || '#000';
        doc.fillColor(color).font('Helvetica-Bold').text(`  ${level} (${dets.length})`);
        doc.fillColor('#000').font('Helvetica');
        for (const d of dets.slice(0, 10)) {
          doc.text(`    - ${d.label} (${(d.confidence * 100).toFixed(1)}%) at frame ${d.frameIndex}`);
        }
        if (dets.length > 10) {
          doc.text(`    ... and ${dets.length - 10} more`);
        }
        doc.moveDown(0.3);
      }
    }

    doc.moveDown(1);

    // Disclaimer
    doc.fontSize(8).font('Helvetica').fillColor('#999');
    doc.text(
      'DISCLAIMER: This report is generated by an AI system and is intended as decision-support only. ' +
      'All findings must be verified by authorized personnel before any action is taken. ' +
      'AI confidence scores are probabilistic and should not be treated as definitive.',
      50,
      doc.y,
      { width: 495 }
    );

    doc.moveDown(0.5);
    doc.text(`Generated: ${new Date().toISOString()} | WildShield AI v0.2.0`);

    doc.end();

    stream.on('finish', async () => {
      try {
        const stats = fs.statSync(filePath);
        const report = await Report.create({
          analysisId,
          generatedBy: userId,
          filename,
          path: filePath,
          fileSize: stats.size,
        });
        await Analysis.findByIdAndUpdate(analysisId, { reportPath: filePath });
        resolve(report);
      } catch (err) {
        reject(err);
      }
    });

    stream.on('error', reject);
  });
}

function formatSize(bytes) {
  if (!bytes) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  let i = 0;
  let size = bytes;
  while (size >= 1024 && i < units.length - 1) {
    size /= 1024;
    i++;
  }
  return `${size.toFixed(1)} ${units[i]}`;
}

module.exports = { generateReport };
